# Generated by Django 3.2.6 on 2021-09-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer'),
        ),
    ]
