# Generated by Django 3.2.6 on 2021-09-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customertransaction_cust_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertransaction',
            old_name='cust_id',
            new_name='customer',
        ),
    ]
