# Generated by Django 3.2.6 on 2021-10-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customerproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.customertransaction'),
        ),
    ]
